---
title: "Gobi"
author: "Marie Hackenberg"
date: "2025-02-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries
```{r}
library(readr)
library(tidyr)
library(dplyr)
```

# Load data
Downloading the bulk data from humet.org as either a csv or an excel file was simple, but the names were swapped, making the files unable to be processed by rstudio. Simply changing the extension solved this issue.
```{r}
data_path <-"/Users/mariehackenberg/Documents/Bioinformatik/9. Semester (WS24:25)/Gobi/humet_data.csv" #Marie
info_path <- "/Users/mariehackenberg/Documents/Bioinformatik/9. Semester (WS24:25)/Gobi/humet_info.csv" #Marie
data <- read_csv(data_path)
info <- read_csv(info_path)

# Filter out unnecessary data
info_plasma <- info %>% filter(fluid == "plasma")

# Remove [P, nt-ms] from column names of metabolites in data
colnames(data) <- gsub(" \\[P, nt-ms\\]$", "", colnames(data))



# Merge data and info by metabolite
#merged_data <- merge(data, info, by = "metabolite")

#data_long <- data %>% pivot_longer(cols = -c(time, subject), # exclude time and subject columns
 #                                  names_to = "metabolite", # name for the metabolite column
  #                                 values_to = "value") # name for the metabolite values

#merged_data <- left_join(data_long, info, by = "metabolite")



```
## Impute missing data (assuming 'data' contains missing values)
```{r}
library(missForest)
imputed_data <- missForest(data)
data_imputed <- imputed_data$ximp
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

